# Generated by Django 5.0.4 on 2024-05-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phones',
            new_name='Products',
        ),
    ]
